{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9008c270",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'airflow'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[1], line 3\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mdatetime\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m datetime, timedelta\n\u001b[0;32m      2\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpathlib\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m Path\n\u001b[1;32m----> 3\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mairflow\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m DAG\n\u001b[0;32m      4\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mairflow\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01moperators\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mbash\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m BashOperator\n\u001b[0;32m      5\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mairflow\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01moperators\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mpython_operator\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m PythonOperator\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'airflow'"
     ]
    }
   ],
   "source": [
    "from datetime import datetime, timedelta\n",
    "from pathlib import Path\n",
    "from airflow import DAG\n",
    "from airflow.operators.bash import BashOperator\n",
    "from airflow.operators.python_operator import PythonOperator\n",
    "from airflow.utils.dates import days_ago\n",
    "\n",
    "\n",
    "import requests\n",
    "import json\n",
    "import pandas as pd\n",
    "import psycopg2\n",
    "\n",
    "def conexion_redshift():\n",
    "    url=\"data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com\"\n",
    "    data_base=\"data-engineer-database\"\n",
    "    user=\"diegoalonsotelloalva1998_coderhouse\"\n",
    "    pwd= 'KTs5N49gGd'\n",
    "\n",
    "    try:\n",
    "        conn = psycopg2.connect(\n",
    "            host='data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com',\n",
    "            dbname=data_base,\n",
    "            user=user,\n",
    "            password=pwd,\n",
    "            port='5439'\n",
    "        )\n",
    "        print(\"Conectado a Redshift con éxito!\")\n",
    "    \n",
    "    except Exception as e:\n",
    "        print(\"No es posible conectar a Redshift\")\n",
    "    \n",
    "    cur.execute(\"\"\"\n",
    "        CREATE TABLE IF NOT EXISTS diegoalonsotelloalva1998_coderhouse.bitcoins\n",
    "        (\n",
    "         compra_bitcon_pesoarg FLOAT\n",
    "        ,comision_bitcon_pesoarg FLOAT \n",
    "        ,venta_bitcon_pesoarg FLOAT \n",
    "        ,compra_trxusdt_pesoarg FLOAT\n",
    "        ,comision_trxusdt_pesoarg FLOAT\n",
    "        ,venta_trxusdt_pesoarg FLOAT\n",
    "        ,fecha_actualizacion VARCHAR(255)\n",
    "        ,comision_retiro FLOAT\n",
    "        )\n",
    "    \"\"\")\n",
    "    conn.commit()\n",
    "\n",
    "def extraer_data_api():\n",
    "    #Paso 1 Extraer la data\n",
    "\n",
    "    data = []\n",
    "\n",
    "    response = requests.get('https://www.bitmonedero.com/api/btc-ars')\n",
    "    data_json = json.loads(response.text)\n",
    "    data.append(data_json)\n",
    "\n",
    "    #Paso 2 Crear el diccionario\n",
    "\n",
    "    diccionario = {'compra_bitcon_pesoarg':[],'comision_bitcon_pesoarg':[],'venta_bitcon_pesoarg':[],'compra_trxusdt_pesoarg':[]\n",
    "                   ,'comision_trxusdt_pesoarg':[],'venta_trxusdt_pesoarg':[],'fecha_actualizacion':[],'comision_retiro':[]}\n",
    "\n",
    "    # compra_bitcon_pesoarg\n",
    "    # comision_bitcon_pesoarg\n",
    "    # venta_bitcon_pesoarg\n",
    "    # compra_trxusdt_pesoarg\n",
    "    # comision_trxusdt_pesoarg\n",
    "    # venta_trxusdt_pesoarg\n",
    "    # fecha_actualizacion\n",
    "    # comision_retiro\n",
    "\n",
    "    #Extraer cada campo de la data\n",
    "\n",
    "    for i in data:\n",
    "        compra_bitcon_pesoarg = i['buy_btc_ars']\n",
    "        comision_bitcon_pesoarg= i['buy_btc_ars_fee']\n",
    "        venta_bitcon_pesoarg= i['sell_btc_ars']\n",
    "        compra_trxusdt_pesoarg= i['buy_trxusdt_ars']\n",
    "        comision_trxusdt_pesoarg = i['buy_trxusdt_ars_fee']\n",
    "        venta_trxusdt_pesoarg= i['sell_trxusdt_ars']\n",
    "        fecha_actualizacion= i['updated_at_prices']\n",
    "        comision_retiro= i['withdrawal_fee']\n",
    "\n",
    "        diccionario['compra_bitcon_pesoarg'].append(compra_bitcon_pesoarg)\n",
    "        diccionario['comision_bitcon_pesoarg'].append(comision_bitcon_pesoarg)\n",
    "        diccionario['venta_bitcon_pesoarg'].append(venta_bitcon_pesoarg)\n",
    "        diccionario['compra_trxusdt_pesoarg'].append(compra_trxusdt_pesoarg)\n",
    "        diccionario['comision_trxusdt_pesoarg'].append(comision_trxusdt_pesoarg)\n",
    "        diccionario['venta_trxusdt_pesoarg'].append(venta_trxusdt_pesoarg)\n",
    "        diccionario['fecha_actualizacion'].append(fecha_actualizacion)\n",
    "        diccionario['comision_retiro'].append(comision_retiro)\n",
    "\n",
    "    df = pd.DataFrame(diccionario)\n",
    "    display(df)\n",
    "\n",
    "def insertando_data_api():\n",
    "    from psycopg2.extras import execute_values\n",
    "    with conn.cursor() as cur:\n",
    "        execute_values(\n",
    "            cur,\n",
    "            '''\n",
    "            INSERT INTO bitcoins (compra_bitcon_pesoarg,comision_bitcon_pesoarg,venta_bitcon_pesoarg,compra_trxusdt_pesoarg\n",
    "            ,comision_trxusdt_pesoarg,venta_trxusdt_pesoarg,fecha_actualizacion,comision_retiro)\n",
    "            VALUES %s\n",
    "            ''',\n",
    "            [tuple(row) for row in df.values],\n",
    "            page_size=len(df)\n",
    "        )\n",
    "        conn.commit()\n",
    "        \n",
    "        cur.close()\n",
    "        conn.close()\n",
    "        \n",
    "## TAREAS\n",
    "\n",
    "default_args = {\n",
    "    'start_date': datetime(2024, 4, 14),\n",
    "    'retries': 1,\n",
    "    'retry_delay': timedelta(minutes=5)\n",
    "}\n",
    "\n",
    "\n",
    "ingestion_dag = DAG(\n",
    "    dag_id='ingestion_data',\n",
    "    default_args=default_args,\n",
    "    description='Agrega datos de los tipos de cambio en bitcoins',\n",
    "     schedule_interval=timedelta(days=1),\n",
    "    catchup=False\n",
    ")\n",
    "\n",
    "\n",
    "task_1 = PythonOperator(\n",
    "    task_id='conexion_redshift',\n",
    "    python_callable=conexion_redshift,\n",
    "    #op_args=[\"{{ ds }} {{ execution_date.hour }}\"],\n",
    "    dag=ingestion_dag,\n",
    ")\n",
    "\n",
    "task_2 = PythonOperator(\n",
    "    task_id='extraer_data_api',\n",
    "    python_callable=extraer_data_api,\n",
    "    dag=ingestion_dag,\n",
    ")\n",
    "\n",
    "task_3 = PythonOperator(\n",
    "    task_id='insertando_data_api',\n",
    "    python_callable=insertando_data_api,\n",
    "    dag=ingestion_dag,\n",
    ")\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "task_1 >> task_2 >> task_3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "b4085034",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.\n",
      "\n",
      "Collecting airflow\n",
      "  Using cached airflow-0.6.tar.gz (1.2 kB)\n",
      "  Preparing metadata (setup.py): started\n",
      "  Preparing metadata (setup.py): finished with status 'error'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  error: subprocess-exited-with-error\n",
      "  \n",
      "  python setup.py egg_info did not run successfully.\n",
      "  exit code: 1\n",
      "  \n",
      "  [14 lines of output]\n",
      "  running egg_info\n",
      "  creating C:\\Users\\Usuario\\AppData\\Local\\Temp\\pip-pip-egg-info-soq_6bu6\\airflow.egg-info\n",
      "  writing C:\\Users\\Usuario\\AppData\\Local\\Temp\\pip-pip-egg-info-soq_6bu6\\airflow.egg-info\\PKG-INFO\n",
      "  writing dependency_links to C:\\Users\\Usuario\\AppData\\Local\\Temp\\pip-pip-egg-info-soq_6bu6\\airflow.egg-info\\dependency_links.txt\n",
      "  writing top-level names to C:\\Users\\Usuario\\AppData\\Local\\Temp\\pip-pip-egg-info-soq_6bu6\\airflow.egg-info\\top_level.txt\n",
      "  writing manifest file 'C:\\Users\\Usuario\\AppData\\Local\\Temp\\pip-pip-egg-info-soq_6bu6\\airflow.egg-info\\SOURCES.txt'\n",
      "  reading manifest file 'C:\\Users\\Usuario\\AppData\\Local\\Temp\\pip-pip-egg-info-soq_6bu6\\airflow.egg-info\\SOURCES.txt'\n",
      "  writing manifest file 'C:\\Users\\Usuario\\AppData\\Local\\Temp\\pip-pip-egg-info-soq_6bu6\\airflow.egg-info\\SOURCES.txt'\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 2, in <module>\n",
      "    File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "    File \"C:\\Users\\Usuario\\AppData\\Local\\Temp\\pip-install-vepmsicd\\airflow_acb13230140641f7b0e5d306568f9552\\setup.py\", line 32, in <module>\n",
      "      raise RuntimeError('Please install package apache-airflow instead of airflow')\n",
      "  RuntimeError: Please install package apache-airflow instead of airflow\n",
      "  [end of output]\n",
      "  \n",
      "  note: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "error: metadata-generation-failed\n",
      "\n",
      "Encountered error while generating package metadata.\n",
      "\n",
      "See above for output.\n",
      "\n",
      "note: This is an issue with the package mentioned above, not pip.\n",
      "hint: See above for details.\n"
     ]
    }
   ],
   "source": [
    "pip install airflow\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ef47e047",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
